import React from 'react';
import { useApp } from '../context/AppContext';
import { Award, Download, Printer, ArrowRight, CheckCircle2, FileText, Sparkles } from 'lucide-react';

export default function ExamResultView() {
  const { exam1Score, registrationData, studentId, navigateTo, showToast } = useApp();

  return (
    <section className="section bg-light">
      <div className="container" style={{ maxWidth: '640px' }}>
        
        {/* Header */}
        <div className="section-header">
          <div className="badge-tag">
            <Sparkles size={14} />
            <span>PDF PAGE 8 REQUIREMENT</span>
          </div>
          <h2 className="section-title">
            Result of Exam 1
          </h2>
          <p className="section-subtitle">
            Screening assessment score overview generated by the ILMI testing system.
          </p>
          <div className="gold-divider" />
        </div>

        {/* Score Card Box matching PDF Page 8 */}
        <div style={{
          backgroundColor: '#FFFFFF',
          borderRadius: 'var(--radius-lg)',
          padding: '2.5rem',
          boxShadow: 'var(--shadow-md)',
          border: '2px solid var(--color-gold)'
        }}>
          
          <div style={{
            backgroundColor: 'var(--color-navy)',
            color: '#FFFFFF',
            borderRadius: 'var(--radius-md)',
            padding: '1.25rem 1.5rem',
            textAlign: 'center',
            marginBottom: '2rem'
          }}>
            <div style={{ fontSize: '0.8rem', color: 'var(--color-gold)', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '1.5px' }}>
              OFFICIAL RESULT CARD
            </div>
            <h3 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#FFFFFF', marginTop: '0.2rem' }}>
              EXAM 1 RESULT
            </h3>
          </div>

          <div style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '0.85rem',
            backgroundColor: 'var(--color-bg-light)',
            padding: '1.5rem',
            borderRadius: 'var(--radius-md)',
            marginBottom: '2rem',
            fontSize: '1.05rem'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed var(--color-border)', paddingBottom: '0.5rem' }}>
              <span style={{ color: 'var(--color-text-muted)' }}>Total Questions:</span>
              <strong style={{ color: 'var(--color-navy)' }}>{exam1Score.totalQuestions}</strong>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed var(--color-border)', paddingBottom: '0.5rem' }}>
              <span style={{ color: 'var(--color-text-muted)' }}>Attempted:</span>
              <strong style={{ color: 'var(--color-navy)' }}>{exam1Score.attempted}</strong>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed var(--color-border)', paddingBottom: '0.5rem' }}>
              <span style={{ color: 'var(--color-text-muted)' }}>Correct:</span>
              <strong style={{ color: '#22c55e' }}>{exam1Score.correct}</strong>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed var(--color-border)', paddingBottom: '0.5rem' }}>
              <span style={{ color: 'var(--color-text-muted)' }}>Wrong:</span>
              <strong style={{ color: '#ef4444' }}>{exam1Score.wrong}</strong>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed var(--color-border)', paddingBottom: '0.5rem' }}>
              <span style={{ color: 'var(--color-text-muted)' }}>Score:</span>
              <strong style={{ color: 'var(--color-navy)', fontSize: '1.15rem' }}>{exam1Score.score}</strong>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed var(--color-border)', paddingBottom: '0.5rem' }}>
              <span style={{ color: 'var(--color-text-muted)' }}>Percentage:</span>
              <strong style={{ color: 'var(--color-gold-dark)', fontSize: '1.15rem' }}>{exam1Score.percentage}%</strong>
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: '0.2rem' }}>
              <span style={{ color: 'var(--color-text-muted)', fontWeight: 700 }}>Status:</span>
              <span style={{
                backgroundColor: 'rgba(34, 197, 94, 0.15)',
                color: '#22c55e',
                border: '1px solid #22c55e',
                padding: '0.35rem 0.85rem',
                borderRadius: 'var(--radius-sm)',
                fontWeight: 800,
                fontSize: '0.95rem'
              }}>
                ✓ {exam1Score.status}
              </span>
            </div>
          </div>

          {/* Action Buttons */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
              <button 
                onClick={() => navigateTo('result-report')}
                className="btn btn-primary"
                style={{ flex: 1 }}
              >
                <Download size={18} />
                <span>Download Result PDF</span>
              </button>

              <button 
                onClick={() => window.print()}
                className="btn btn-outline"
                style={{ flex: 1 }}
              >
                <Printer size={18} />
                <span>Print Result</span>
              </button>
            </div>

            <button 
              onClick={() => navigateTo('student-portal', { tab: 'dashboard' })}
              className="btn btn-navy"
              style={{ width: '100%' }}
            >
              <span>Return to Student Dashboard</span>
              <ArrowRight size={18} />
            </button>
          </div>

        </div>

      </div>
    </section>
  );
}
